### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by grogcw** [nmosier/86x64#1]
Hi !

I'm trying to compile on Mojave and I run into git checkouts problems.

```
CMake Error at /Users/me/86x64/build/extern/xed/tmp/mbuild-gitclone.cmake:40 (message):
  Failed to checkout tag: 'master'
```

```
CMake Error at /Users/me/86x64/build/extern/xed/tmp/mbuild-gitupdate.cmake:175 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 1"
```

I then tried to git clone manually for xed and mbuild, but when I try to make I've got the following error :

```
[  4%] No configure step for 'xed'
/bin/sh: line 0: cd: /Users/me/86x64/build/extern/xed/src/xed-build: No such file or directory
make[2]: *** [extern/xed/src/xed-stamp/xed-configure] Error 1
make[1]: *** [extern/CMakeFiles/xed.dir/all] Error 2
make: *** [all] Error 2
```

I think that external gits have changed and / or the makefile is wrong somewhere ?

Do you have any idea ?

Thanks for taking care,

Cheers !

**Comment by nmosier** [comment]
You're right -- the Intel XED branch names changed. I think I fixed it -- try compiling now.

**Comment by grogcw** [comment]
Ok, the git does get pulled and compiles fine.

Another problem has emerged though : 

```
[ 18%] Built target syscall_tabgen
make[2]: *** No rule to make target `tests/file.c', needed by `tests/file-O0-32.o'.  Stop.
make[1]: *** [tests/CMakeFiles/file-O0.dir/all] Error 2
make: *** [all] Error 2
```

Your git is freshly pulled with the update, and there is a "file.c" in the src/tests folder.

I snooped around and I think that the problem is in the tests/CMakeList.txt, particularly line 17 :

`create_test(file exit printf-many printf sum sprintf fprintf myls in_addr mysh)`

If I comment it out, there is no problem and the compile goes thru - and installs fine.
